addons:
  ssh_known_hosts: git.example.com

script:
  - mkdir ~/.ssh
  - echo -e $MYPROJECT_CI_PRIVATE_KEY > ~/.ssh/id_rsa_myproject_ci
  - chmod 600 ~/.ssh/id_rsa_myproject_ci
  - echo -e "Host myproject-ci-bitbucket\n HostName bitbucket.org\n User git\n IdentityFile ~/.ssh/id_rsa_myproject_ci\n StrictHostKeyChecking no" > ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - git clone https://github.com/fabrizio2210/docker-HA_volume_sync_deployer.git
  - git checkout armv7hf
  - git submodule update --init --recursive
  - git commit -a -m "auto commit for changing sources"
  - git push origin armv7hf
