addons:
  ssh_known_hosts: github.com

language: generic

script:
  - ./travis/update-topmodules.sh "$MYPROJECT_CI_PRIVATE_KEY" 'https://github.com/fabrizio2210/docker-HA_volume_sync_deployer.git;armv7hf:src'
