addons:
  ssh_known_hosts: github.com

language: generic

script:
  - mkdir ~/.ssh
  - echo -e $MYPROJECT_CI_PRIVATE_KEY > /tmp/id_rsa
  - base64 -d /tmp/id_rsa > ~/.ssh/id_rsa_myproject_ci
  - chmod 600 ~/.ssh/id_rsa_myproject_ci
  - echo -e "Host github.com\n User git\n IdentityFile ~/.ssh/id_rsa_myproject_ci\n StrictHostKeyChecking no" > ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - git clone https://github.com/fabrizio2210/docker-HA_volume_sync_deployer.git
  - cd docker-HA_volume_sync_deployer/
  - git checkout armv7hf
  - git submodule update --init --recursive
  - cd src
  - git fetch
  - git checkout master
  - cd ..
  - git commit -a -m "auto commit for changing sources"
  - sed -i 's/https:\/\/github.com\//git@github.com:/' .git/config
  - git push origin armv7hf
